version: "3.9"
services:
  series-app-back:
    image: imagen-series-back
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mysql://series-app-db:3306/tp_integrador2
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - series-app-db
  series-app-db:
    image: mysql/mysql-server:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=tp_integrador2
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - C:/Users/dagudo/Documents/AcademIT2/Integrador/Proyecto/Series_app_ETAPA2/bd_dockerizada:/var/lib/mysql
